name: neat_cli
description: Neat, Create FLutter Clean Archtecture Projects with bloc.
version: 0.0.4
homepage: https://github.com/MerseniBilel/neat_cli.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.1.1
  process_run: ^0.12.3+2
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

executables:
  neat_cli: